# Generated by Django 5.0.6 on 2024-06-11 10:17

import site_setup.utils.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_alter_sitesetup_options_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='asserts/favicon/%Y/%m/', validators=[site_setup.utils.model_validators.validate_png]),
        ),
    ]
